// ===== DỮ LIỆU CÂU HỎI =====

const MC_B11 = [
  { q: "Cuộc cải cách hành chính lớn nhất của vương triều Nguyễn được tiến hành dưới thời vua", opts: ["Gia Long.", "Minh Mạng.", "Tự Đức.", "Thiệu Trị."], ans: 1 },
  { q: "Cuộc cải cách của vua Minh Mạng (nửa đầu thế kỉ XIX) được thực hiện trong bối cảnh lịch sử nào sau đây?", opts: ["Chế độ quân chủ chuyên chế đang trong thời kì thịnh trị.", "Phương thức sản xuất tư bản chủ nghĩa phát triển mạnh.", "Bộ máy chính quyền nhà nước chưa hoàn thiện, đồng bộ.", "Đất nước đứng trước nguy cơ xâm lược từ nhà Thanh."], ans: 2 },
  { q: "Cuộc cải cách của vua Minh Mạng (nửa đầu thế kỉ XIX) nhằm thực hiện một trong những mục đích nào sau đây?", opts: ["Tập trung quyền lực vào tay vua.", "Thúc đẩy kinh tế tư bản chủ nghĩa.", "Ngăn ngừa nguy cơ giặc ngoại xâm.", "Khôi phục nền giáo dục Nho học."], ans: 0 },
  { q: "Để hoàn thiện bộ máy chính quyền Trung ương, vua Minh Mạng đã cho thành lập một số cơ quan mới có tên là", opts: ["Lục bộ, Lục khoa, Lục tự.", "Đô ty, Thừa ty, Hiến ty.", "Đô sát viện, Cơ mật viện.", "Thông chính ty, Quốc Tử Giám."], ans: 2 },
  { q: "Cuộc cải cách của vua Minh Mạng (nửa đầu thế kỉ XIX) tập trung vào lĩnh vực chủ yếu nào sau đây?", opts: ["Kinh tế.", "Văn hóa.", "Quốc phòng.", "Hành chính."], ans: 3 },
  { q: "Trong cuộc cải cách nửa đầu thế kỉ XIX, vua Minh Mạng đã phân chia bộ máy chính quyền địa phương thành các cấp nào sau đây?", opts: ["Đạo thừa tuyên, phủ, huyện/châu, xã.", "Tỉnh/thành phố, huyện/châu, xã.", "Lộ, trấn, phủ, huyện/châu, xã.", "Tỉnh, phủ, huyện/châu, tổng, xã."], ans: 3 },
  { q: "Nội dung nào sau đây KHÔNG phải là hoạt động cải cách của vua Minh Mạng nửa đầu thế kỉ XIX?", opts: ["Hoàn thiện cơ cấu, chức năng của Lục bộ.", "Ban hành chính sách hạn điền và hạn nô.", "Tăng cường giám sát lẫn nhau giữa các cơ quan.", "Phân chia lại đơn vị hành chính ở cấp địa phương."], ans: 1 },
  { q: "Trong công cuộc cải cách của vua Minh Mạng, Nội các được thành lập có vai trò nào sau đây?", opts: ["Giúp vua khởi thảo các văn bản hành chính.", "Kiểm tra, giám sát hoạt động của Lục bộ.", "Phụ trách nhân khẩu, thu thuế trong cả nước.", "Xướng danh những người đỗ trong kì thi Đình."], ans: 0 },
  { q: "Năm 1832, vua Minh Mạng cho thành lập Đô sát viện để thực hiện nhiệm vụ nào sau đây?", opts: ["Tiếp nhận và xử lý các loại công văn, giấy tờ.", "Can gián nhà vua và giám sát các cơ quan.", "Phụ trách nhân khẩu, thu thuế trong cả nước.", "Phụ trách bang giao, đón tiếp sứ thần nước ngoài."], ans: 1 },
  { q: "Trong cải cách của vua Minh Mạng (nửa đầu thế kỉ XIX), đứng đầu tỉnh là", opts: ["Đô ty, Thừa ty, Hiến ty.", "Lục bộ, Lục khoa.", "Tổng đốc, Tuần phủ.", "Lục khoa, Lục tự."], ans: 2 },
  { q: "Công cuộc cải cách của vua Minh Mạng (nửa đầu thế kỉ XIX) đã đem lại một trong những kết quả nào sau đây?", opts: ["Đưa đất nước phát triển lên chế độ tư bản chủ nghĩa.", "Thúc đẩy bộ máy chính quyền các cấp hoạt động hiệu quả.", "Góp phần mở cửa và hội nhập nền kinh tế khu vực.", "Hoàn thành thống nhất đất nước về mặt lãnh thổ."], ans: 1 },
  { q: "Nội dung nào sau đây KHÔNG phản ánh đúng kết quả cuộc cải cách của vua Minh Mạng (nửa đầu thế kỉ XIX)?", opts: ["Xây dựng được chế độ quân chủ trung ương tập quyền cao độ.", "Thống nhất đơn vị hành chính địa phương trong cả nước.", "Tổ chức cơ cấu bộ máy nhà nước gọn nhẹ, chặt chẽ.", "Xây dựng chế độ quân chủ trung ương phân quyền cao độ."], ans: 3 },
  { q: "Ở địa phương, trong công cuộc cải cách hành chính nửa đầu thế kỉ XIX, vua Minh Mạng đã chia cả nước thành", opts: ["30 tỉnh và 1 phủ Thừa Thiên.", "Bắc Thành, Gia Định thành.", "13 đạo thừa tuyên và các phủ.", "Các lộ, trấn, phủ, huyện/châu."], ans: 0 },
  { q: "Cuộc cải cách của vua Minh Mạng (nửa đầu thế kỉ XIX) được thực hiện trong bối cảnh", opts: ["Tình hình an ninh – xã hội ở nhiều địa phương bất ổn.", "Bộ máy nhà nước phong kiến cơ bản đã hoàn chỉnh.", "Tình trạng phân quyền, thiếu thống nhất đã khắc phục.", "Phương thức sản xuất tư bản chủ nghĩa thâm nhập mạnh."], ans: 0 },
  { q: "Cuộc cải cách hành chính của vua Minh Mạng (nửa đầu thế kỉ XIX) KHÔNG nhằm mục đích nào sau đây?", opts: ["Khắc phục tình trạng phân quyền, thiếu thống nhất.", "Tăng cường tính thống nhất và tiềm lực của đất nước.", "Tập trung quyền lực và hoàn thiện bộ máy nhà nước.", "Xóa bỏ tình trạng \"bế quan tỏa cảng\" của đất nước."], ans: 3 },
  { q: "Cuộc cải cách của vua Minh Mạng (nửa đầu thế kỉ XIX) có ý nghĩa quan trọng nào sau đây?", opts: ["Xóa bỏ tình trạng \"bế quan tỏa cảng\" của đất nước.", "Ngăn chặn mọi nguy cơ xâm lược từ bên ngoài.", "Đặt cơ sở cho sự phân chia tỉnh, huyện hiện nay.", "Hoàn thành thống nhất đất nước về mặt lãnh thổ."], ans: 2 },
  { q: "Cuộc cải cách của vua Minh Mạng và cuộc cải cách của vua Lê Thánh Tông (thế kỉ XV) có điểm giống nhau nào sau đây?", opts: ["Nâng cao vai trò quản lí của chính quyền ở trung ương.", "Khuyến khích, tạo điều kiện cho ngoại thương phát triển.", "Ưu tiên cho sự nghiệp thống nhất đất nước về lãnh thổ.", "Chú trọng phát triển kinh tế, xã hội theo hướng tư bản."], ans: 0 },
  { q: "Một trong những di sản lớn nhất trong cuộc cải cách của vua Minh Mạng còn giá trị đến ngày nay là", opts: ["Cách thức tổ chức bộ máy nhà nước ở trung ương.", "Cách thức phân chia đơn vị hành chính cấp tỉnh.", "Tập trung cao độ quyền lực vào trong tay nhà vua.", "Ưu tiên bổ nhiệm quan lại là người ở địa phương."], ans: 1 },
  { q: "Một trong những hạn chế trong cải cách của vua Minh Mạng nửa đầu thế kỉ XIX là", opts: ["Cải cách nặng về củng cố vương triều, ít chú ý đến cải thiện dân sinh.", "Cải cách làm tăng thêm tình trạng cát cứ, phân quyền ở các địa phương.", "Sự giám sát, ràng buộc lẫn nhau giữa các cơ quan, chức quan mờ nhạt.", "Bộ máy nhà nước cồng kềnh, hoạt động kém hiệu quả hơn thời kì trước."], ans: 0 },
  { q: "Dưới thời Minh Mạng, triều đình tăng cường quyền kiểm soát đối với vùng dân tộc thiểu số thông qua việc", opts: ["Thiết lập chế độ thổ quan.", "Bãi bỏ quyền thế tập của tù trưởng.", "Gả công chúa cho các tù trưởng.", "Bỏ lưu quan (quan lại người Kinh)."], ans: 1 },
  { q: "Một trong những tác dụng tích cực của cải cách hành chính thời vua Minh Mạng là góp phần", opts: ["Tạo điều kiện phát triển kinh tế theo hướng tư bản.", "Hạn chế sự tham nhũng và lộng hành của quan lại.", "Khích lệ người dân tích cực thi cử và ra làm quan.", "Phát triển nền văn hóa mang đậm bản sắc dân tộc."], ans: 1 },
  { q: "Vua Minh Mạng cải cách hệ thống chính trị - hành chính chặt chẽ, gọn nhẹ từ trung ương đến địa phương KHÔNG nhằm mục tiêu nào dưới đây?", opts: ["Nâng cao năng lực hệ thống quan chức ở trung ương.", "Thống nhất đất nước, xác lập chủ quyền lãnh thổ.", "Thiết lập nên nhà nước quân chủ phong kiến tập quyền.", "Hạn chế tối đa quyền tự trị của làng xã, địa phương."], ans: 3 },
  { q: "Khó khăn lớn nhất của Triều Nguyễn khi mới thành lập vào năm 1802 là gì?", opts: ["Đất nước vừa trải qua thời kỳ chiến tranh dài.", "Thiếu nguồn nhân lực để khai phá đất đai mới.", "Quan hệ ngoại giao với láng giềng bị rạn nứt.", "Hệ thống đê điều tại Bắc Hà bị hư hỏng nặng."], ans: 0 },
  { q: "Đặc điểm nổi bật của bộ máy hành chính nhà nước thời đầu nhà Nguyễn là gì?", opts: ["Đã được hoàn thiện một cách rất chặt chẽ.", "Hệ thống cơ quan trung ương rất tinh gọn.", "Bộ máy nhà nước lúc này chưa được hoàn chỉnh.", "Các cơ quan chuyên môn hoạt động rất hiệu quả."], ans: 2 },
  { q: "Lực lượng nào nắm giữ vai trò chủ yếu trong bộ máy nhà nước thời đầu nhà Nguyễn?", opts: ["Các văn thần có học vấn cao trong triều đình.", "Các võ quan nắm giữ phần lớn chức vụ quan trọng.", "Các thành viên thuộc hoàng tộc nhà Nguyễn.", "Các thương nhân có đóng góp lớn cho đất nước."], ans: 1 },
  { q: "Việc tồn tại các \"Thành\" (Bắc Thành, Gia Định Thành) cho thấy điều gì?", opts: ["Sự thống nhất hoàn toàn của bộ máy nhà nước trung ương.", "Sự tập trung quyền lực tuyệt đối vào tay nhà vua trẻ.", "Sự chưa thống nhất trong tổ chức hành chính giữa các khu vực.", "Sự phát triển vượt bậc của các đô thị lớn ở hai đầu đất nước."], ans: 2 },
  { q: "Tại sao vua Minh Mạng lại muốn xóa bỏ chế độ phân quyền ở địa phương?", opts: ["Để giảm bớt gánh nặng chi phí cho ngân sách hoàng gia.", "Để tăng cường sự quản lý trực tiếp của triều đình trung ương.", "Để tạo điều kiện cho các quan văn thay thế các võ quan.", "Để chuẩn bị cho việc dời đô từ Huế ra khu vực Thăng Long."], ans: 1 },
  { q: "Tình trạng \"thiếu thống nhất\" trong bộ máy nhà nước thể hiện rõ nhất ở đâu?", opts: ["Trong việc ban hành các chính sách về tôn giáo và tín ngưỡng.", "Trong tổ chức hành chính giữa các khu vực khác nhau của đất nước.", "Trong cách thức tuyển chọn quan lại thông qua các kỳ thi cử.", "Trong việc quy định các loại thuế đối với nông dân và thợ thủ công."], ans: 1 },
  { q: "So với thời vua Gia Long, điểm khác biệt trong trọng tâm cai trị của vua Minh Mạng là gì?", opts: ["Từ mở rộng lãnh thổ sang bảo vệ biên giới phía Bắc.", "Từ ổn định tình hình sang hoàn thiện bộ máy nhà nước.", "Từ trọng dụng võ quan sang tiêu diệt các tướng lĩnh cũ.", "Từ xây dựng kinh thành sang phát triển giao thương biển."], ans: 1 },
  { q: "Ý nghĩa quan trọng nhất của cuộc cải cách đối với đơn vị hành chính là gì?", opts: ["Giảm bớt số lượng các tỉnh và thành phố.", "Hoàn thành thống nhất đất nước về hành chính.", "Tạo ra sự cân bằng giữa các vùng miền khác.", "Tăng cường quyền tự trị cho các cấp cơ sở."], ans: 1 },
  { q: "Bài học kinh nghiệm quý báu nhất về tổ chức bộ máy nhà nước từ cuộc cải cách là gì?", opts: ["Cần phải tăng cường số lượng quan lại ở địa phương.", "Phải xác định rõ chức năng, nhiệm vụ của từng cơ quan.", "Nên tập trung quyền lực vào một vài cá nhân kiệt xuất.", "Chỉ tập trung vào việc hiện đại hóa lực lượng quân đội."], ans: 1 },
];

const TF_B11 = [
  { q: "Đọc đoạn tư liệu sau đây:\n\"Nội các là một cơ yếu, phải đặc cách chọn lấy những bề tôi chầu hầu tùy tùng ở bên nhà vua khiến cho ra vào gần gụi đề phòng khi cần hỏi han. Những người sung vào chức đó thì lấy ở hàng quan Tam, Tứ phẩm trong các bộ, các viện, còn các thuộc viên thì lấy những người có chức hàm trong Viện hàn lâm sung vào, các bậc thì ở dưới Lục bộ. Phàm những sắc, chiếu, sớ tấu, sách vở, ghi chép, hoặc xem xét giấy tờ, đều thuộc tòa Nội các cả; những viên chức đó đều tùy theo công việc nặng nhẹ, nhiều ít, chước lượng mà chia ra từng tào để cho có chuyên trách\".\n(Lời dụ của Minh Mạng, trích trong: Quốc sử quán triều Nguyễn, Đại Nam thực lục, Tập 3, NXB Giáo dục, Hà Nội, 2004)", items: [
    { text: "Nội các là một trong những cơ quan chủ chốt của triều đình phong kiến trung ương nhà Nguyễn từ thời vua Minh Mạng.", ans: true },
    { text: "Toàn bộ các thành viên của Nội các đều lấy từ các chức quan ở trong Lục bộ.", ans: false },
    { text: "Theo lời dụ của Minh Mạng, một trong những nhiệm vụ của Nội các là giúp vua khởi thảo sắc, chiếu, sớ tấu…", ans: true },
    { text: "Nội các chịu trách nhiệm trực tiếp trước nhà vua, đồng thời chịu sự giám sát của Lục bộ và các cơ quan chuyên môn khác.", ans: false }
  ]},
  { q: "Đọc đoạn tư liệu sau đây:\nTừ năm 1832, đại diện của Đô sát viện, bộ Hình và Đại lý tự tạo thành Tam pháp ty – cơ quan chuyên nhận đơn của những người kêu oan, tố cáo, đồng thời thẩm tra, xét xử những việc oan ức. Hàng tháng, vào các ngày 6, 16, 26 âm lịch, Tam pháp ty họp để xét xử. Nếu không đúng những ngày đó, người đưa đơn có thể đến trước của Tam pháp ty đánh trống Đăng Văn để báo hiệu. Trống Đăng Văn đã phát huy được chức năng trong việc tạo điều kiện cho dân chúng thể hiện tiếng nói của mình mỗi khi bị kết án oan. Đồng thời, sự tồn tại của trống Đăng Văn đã phần nào hạn chế sự chuyên quyền, độc đoán và thói ức hiếp dân chúng của một số quan lại địa phương, thể hiện được sự nghiêm minh của pháp luật thời bấy giờ.", items: [
    { text: "Đoạn trích tập trung phản ánh sự bất cập, hạn chế trong xử lý các hình án dưới thời kì nhà Nguyễn.", ans: false },
    { text: "Tam pháp ty được tạo nên bởi các thành viên của 3 cơ quan, gồm: Đô sát viện, bộ Hình và Đại lý tự.", ans: true },
    { text: "Trống Đăng Văn có thể coi là một biểu tượng dân chủ dưới triều Nguyễn, góp phần hạn chế sự chuyên quyền, độc đoán của một số quan lại.", ans: true },
    { text: "Tam pháp ty là cơ quan chuyên nhận đơn của những người kêu oan và họp bàn xét xử vào một số ngày cố định trong tháng.", ans: true }
  ]},
  { q: "Đọc đoạn tư liệu sau đây:\nDưới thời vua Minh Mạng, đứng đầu tỉnh là Tổng đốc (phụ trách một tỉnh lớn và một tỉnh nhỏ liền kề) hoặc Tuần phủ (phụ trách một tỉnh nhỏ). Hai cơ quan giúp việc cho Tổng đốc và Tuần phủ là Bố chính ty (do Bố chính sứ đứng đầu) và Án sát ty (do Án sát sứ đứng đầu). Bố chính ty phụ trách thuế khóa, đinh điền, hộ tịch. Án sát ty phụ trách hình án.", items: [
    { text: "Đoạn trích phản ánh bộ máy chính quyền dưới thời vua Minh Mạng ở cấp trung ương.", ans: false },
    { text: "Một trong những cải cách hành chính của vua Minh Mạng là chia nước ta ra thành các tỉnh.", ans: true },
    { text: "Dưới thời vua Minh Mạng, Bố chính ty và Án sát ty là hai cơ quan giúp việc cho người đứng đầu cấp tỉnh.", ans: true },
    { text: "Tổng đốc thường là người phụ trách hai tỉnh, trực tiếp cai trị một tỉnh. Tỉnh còn lại do Tuần phủ đứng đầu, đặt dưới sự kiêm quản của Tổng đốc.", ans: true }
  ]},
  { q: "Đọc đoạn tư liệu sau đây:\nNăm 1802, nhà Nguyễn thành lập với lãnh thổ mới rộng lớn, kéo dài từ ải Nam Quan đến mũi Cà Mau. Thời gian đầu, bộ máy chính quyền về cơ bản tiếp tục kế thừa mô hình nhà Lê trung hưng kết hợp với một số biện pháp tạm thời. Thời Gia Long, triều đình trung ương ở Phú Xuân chỉ trực tiếp kiểm soát 4 dinh và 7 trấn từ Thanh Hóa đến Bình Thuận. Quản lý 11 trấn ở phía bắc là Bắc Thành, quản lý 5 trấn ở phía nam là Gia Định Thành. Đứng đầu Bắc Thành và Gia Định Thành là chức Tổng trấn.", items: [
    { text: "Đoạn trích cung cấp thông tin về tình hình nhà Nguyễn dưới thời vua Gia Long trên các mặt chính trị, kinh tế, xã hội.", ans: false },
    { text: "Bộ máy chính quyền dưới thời vua Gia Long thiếu sự thống nhất và đồng bộ trên phạm vi cả nước.", ans: true },
    { text: "Dưới thời vua Gia Long, quyền lực của nhà vua và triều đình phong kiến trung ương bị hạn chế.", ans: true },
    { text: "Sự tồn tại của Bắc Thành và Gia Định thành bộc lộ tính phân quyền và tiềm ẩn nhiều nguy cơ lạm quyền ở địa phương.", ans: true }
  ]},
  { q: "Đọc đoạn tư liệu sau đây:\n\"Trong thì Nội các ở bên tả, Cơ mật viện ở bên hữu, ngoài thì võ có Ngũ quân Đô thống phủ, văn có đường quan Lục bộ: tả hữu có người, trong ngoài giúp nhau. Phàm những việc Lục bộ làm chưa đúng, thì Nội các hạch ra, những việc Nội các làm chưa hợp lẽ thì Cơ mật viện hạch ra, khiến cho ràng rịt nhau mới mong đến được thịnh trị\".\n(Lời dụ của Minh Mạng, trích trong: Quốc sử quán triều Nguyễn, Đại Nam thực lục, Tập 3, NXB Giáo dục, Hà Nội, 2004, tr.435)", items: [
    { text: "Lời dụ của vua Minh Mạng phản ánh tổ chức bộ máy chính quyền phong kiến ở cấp trung ương và địa phương.", ans: false },
    { text: "Nội các, Cơ mật viện, Lục bộ là những cơ quan chủ chốt trực tiếp giúp việc cho vua và chịu trách nhiệm trước nhà vua.", ans: true },
    { text: "Vua Minh Mạng rất coi trọng việc kiểm tra, giám sát lẫn nhau giữa các cơ quan chủ chốt trong triều.", ans: true },
    { text: "Ngũ quân Đô thống phủ là cơ quan chuyên môn giúp đỡ Lục bộ về tổ chức quân đội, võ bị ở các địa phương.", ans: false }
  ]}
];

const MC_B12 = [
  { q: "Biển Đông là vùng biển thuộc", opts: ["Ấn Độ Dương.", "Thái Bình Dương.", "Đại Tây Dương.", "Địa Trung Hải."], ans: 1 },
  { q: "Về vị trí địa lý, biển Đông được coi là cầu nối giữa Thái Bình Dương và", opts: ["Bắc Băng Dương.", "Ấn Độ Dương.", "Đại Tây Dương.", "Địa Trung Hải."], ans: 1 },
  { q: "Biển Đông là vùng biển chung của 9 quốc gia ở châu Á, trong đó có", opts: ["Trung Quốc.", "Lào.", "Ấn Độ.", "Nhật Bản."], ans: 0 },
  { q: "Phía tây nam của biển Đông nối với biển An-đa-man của Ấn Độ Dương thông qua eo biển", opts: ["La-li-man-tan.", "Ma-lắc-ca.", "Lu-dông.", "Đài Loan."], ans: 1 },
  { q: "Tuyến đường vận tải quốc tế qua Biển Đông được coi là nhộn nhịp thứ 2 trên thế giới chỉ sau biển", opts: ["Địa Trung Hải.", "Hoa Đông.", "Caribê.", "Gia-va."], ans: 0 },
  { q: "Eo biển Ma-lắc-ca là điểm điều tiết giao thông quan trọng bậc nhất ở châu lục nào sau đây?", opts: ["Châu Âu.", "Châu Mĩ.", "Châu Phi.", "Châu Á."], ans: 3 },
  { q: "Biển Đông là một trong những biển lớn và là đường vận chuyển huyết mạch của khu vực", opts: ["Châu Á - Thái Bình Dương.", "Bắc Mĩ và eo biển Đan Mạch.", "Châu Âu và mũi Hảo Vọng.", "Châu Phi và châu Nam Cực."], ans: 0 },
  { q: "Biển Đông có ảnh hưởng trực tiếp tới cuộc sống của người dân ở một số nước thuộc khu vực nào sau đây?", opts: ["Châu Phi.", "Châu Mĩ.", "Châu Âu.", "Châu Á."], ans: 3 },
  { q: "Biển Đông là vùng biển chung của 9 quốc gia ở châu Á, trong đó có", opts: ["Ma-lai-xi-a.", "Mĩ.", "Liên bang Nga.", "Mi-an-ma."], ans: 0 },
  { q: "Các cảng biển lớn trên Biển Đông có vai trò nào sau đây?", opts: ["Điểm trung chuyển của tàu thuyền.", "Nơi khai thác và chế biến dầu khí.", "Điểm tập trung phát triển du lịch.", "Nơi giải quyết các vấn đề xã hội."], ans: 0 },
  { q: "Eo biển Ma-lắc-ca là điểm điều tiết giao thông đường biển quan trọng, kết nối nhiều nước châu Á, trong đó có 3 nước đông dân của thế giới là In-đô-nê-xi-a, Trung Quốc và", opts: ["Ai Cập.", "Liên bang Nga.", "Ấn Độ.", "Mông Cổ."], ans: 2 },
  { q: "Vùng biển nào sau đây là tuyến đường di chuyển ngắn nhất nối Thái Bình Dương và Ấn Độ Dương?", opts: ["Biển Địa Trung Hải.", "Biển Đông.", "Biển Đỏ.", "Biển Đen."], ans: 1 },
  { q: "Trong lịch sử, Biển Đông được coi là tuyến đường thiết yếu trong giao thông, giao thương, di cư,…giữa", opts: ["Trung Quốc và Nhật Bản.", "Trung Quốc và Đông Á.", "Ấn Độ và Nam Á.", "Ấn Độ và Trung Quốc."], ans: 3 },
  { q: "Các quốc gia ở khu vực nào sau đây có nền kinh tế gắn trực tiếp với con đường thương mại, hệ thống cảng biển và tài nguyên trên Biển Đông?", opts: ["Đông Bắc Á và Tây Âu.", "Đông Bắc Á và Đông Nam Á.", "Đông Nam Á và Nam Á.", "Nam Á và Tây Á."], ans: 1 },
  { q: "Ở Biển Đông, nguồn tài nguyên thiên nhiên nào sau đây có trữ lượng vào loại lớn nhất thế giới?", opts: ["Muối biển.", "Băng cháy.", "Dầu khí.", "Quặng sắt."], ans: 2 },
  { q: "Nội dung nào sau đây phản ánh đúng sự phong phú về nguồn tài nguyên thiên nhiên của Biển Đông?", opts: ["Biển Đông là điểm điều tiết giao thông đường biển quan trọng nhất châu Á.", "Biển Đông có hàng trăm loài sinh vật, bao gồm cả động vật và thực vật.", "Biển Đông là địa bàn cạnh tranh ảnh hưởng truyền thống của các nước lớn.", "Biển Đông là nơi tập trung các mô hình chính trị, kinh tế xã hội đa dạng."], ans: 1 },
  { q: "Nội dung nào sau đây KHÔNG phản ánh đúng vai trò quan trọng của Biển Đông về mặt kinh tế?", opts: ["Biển Đông là nơi diễn ra quá trình giao thoa của nhiều nền văn hóa lớn.", "Biển Đông là tuyến đường vận tải hàng hải nhộn nhịp thứ hai thế giới.", "Các nước Đông Nam Á ven biển hưởng lợi trực tiếp về kinh tế từ biển Đông.", "Các nước ven biển Đông có hoạt động khai thác hải sản và dầu khí sôi động."], ans: 0 },
  { q: "Ngành kinh tế nào sau đây của Biển Đông được đẩy mạnh nhờ hệ sinh vật đa dạng dưới đáy biển và cảnh quan thiên nhiên tươi đẹp?", opts: ["Du lịch biển.", "Nuôi trồng thủy, hải sản.", "Khai thác khoáng sản.", "Đánh bắt cá."], ans: 0 },
  { q: "Nội dung nào sau đây thể hiện tầm quan trọng chiến lược của Biển Đông?", opts: ["Là tuyến hàng hải quốc tế nhộn nhịp nhất trên thế giới.", "Là tuyến hàng hải nối Thái Bình Dương với Bắc Băng Dương.", "Có nguồn tài nguyên thiên nhiên biển phong phú.", "Là tuyến giao thông hàng hải duy nhất trên biển."], ans: 2 },
  { q: "Nguồn tài nguyên khoáng sản đa dạng trên biển Đông là điều kiện thuận lợi để các nước", opts: ["Kiểm soát, đảm bảo an ninh giao thông trên biển.", "Xây dựng cơ sở hậu cần, kỹ thuật, phục vụ quân sự.", "Phát triển hoạt động kinh tế có tầm chiến lược.", "Xây dựng các trạm thông tin, trạm dừng chân."], ans: 2 },
  { q: "Quần đảo Hoàng Sa và quần đảo Trường Sa thuộc chủ quyền của quốc gia nào sau đây?", opts: ["Trung Quốc.", "Hàn Quốc.", "Việt Nam.", "Nhật Bản."], ans: 2 },
  { q: "Hiện nay, quần đảo Hoàng Sa trực thuộc quyền quản lý hành chính của", opts: ["Thành phố Đà Nẵng.", "Tỉnh Bà Rịa – Vũng Tàu.", "Tỉnh Cà Mau.", "Tỉnh Khánh Hòa."], ans: 0 },
  { q: "Hiện nay, quần đảo Trường Sa trực thuộc quyền quản lí hành chính của", opts: ["Thành phố Đà Nẵng.", "Tỉnh Kiên Giang.", "Tỉnh Khánh Hòa.", "Tỉnh Nghệ An."], ans: 2 },
  { q: "Nội dung nào sau đây phản ánh đúng tầm quan trọng của quần đảo Hoàng Sa và Trường Sa đối với Việt Nam về mặt quốc phòng – an ninh?", opts: ["Xây dựng các trạm thông tin, dừng chân, tiếp nhiên liệu cho các tàu.", "Hình thành tuyến phòng thủ nhiều tầng, từ xa đến gần bảo vệ đất liền.", "Tạo thế mạnh cho dịch vụ hàng hải và đánh bắt hải sản trong khu vực.", "Giúp xây dựng các khu bảo tồn, trung tâm nghiên cứu sinh vật biển."], ans: 1 },
  { q: "Nội dung nào sau đây KHÔNG phản ánh đúng tầm quan trọng của quần đảo Hoàng Sa và Trường Sa đối với Việt Nam về mặt kinh tế?", opts: ["Tạo thế mạnh về dịch vụ hàng hải cho nước ta trên Biển Đông.", "Tạo tuyến phòng thủ nhiều tầng từ xa đến gần để bảo vệ đất liền.", "Tạo thế mạnh để phát triển kinh tế du lịch biển đảo cho nước ta.", "Tạo thuận lợi để phát triển ngành nuôi trồng, chế biến thủy sản."], ans: 1 },
  { q: "Tầm quan trọng chiến lược của quần đảo Hoàng Sa và Trường Sa được thể hiện ở nội dung nào sau đây?", opts: ["Đây là hai quần đảo duy nhất thuộc khu vực Biển Đông.", "Đây là hai quần đảo lớn nhất thuộc khu vực Biển Đông.", "Phục vụ tuyến hàng hải huyết mạch trên Biển Đông.", "Là nơi tiếp nhiên liệu duy nhất cho các tàu trên biển."], ans: 2 },
  { q: "Đối với Việt Nam, tầm quan trọng chiến lược của quần đảo Trường Sa và quần đảo Hoàng Sa được thể hiện ở điểm nào sau đây?", opts: ["Là tuyến đường duy nhất để Việt Nam xuất khẩu hàng nông sản.", "Đảm bảo nguồn an ninh lương thực cho nhân dân Việt Nam.", "Có ý nghĩa về chiến lược quốc phòng, an ninh, kinh tế biển.", "Là nền tảng duy nhất để Việt Nam phát triển công nghiệp nặng."], ans: 2 },
  { q: "Nội dung nào sau đây phản ánh đúng về tầm quan trọng chiến lược của Biển Đông đối với sự phát triển kinh tế Việt Nam?", opts: ["Hệ thống đảo, quần đảo trên Biển Đông chỉ thuận lợi để đầu tư và phát triển du lịch.", "Việt Nam được đánh giá là quốc gia có lợi thế và tiềm năng to lớn về tài nguyên biển.", "Vùng biển rộng lớn với nhiều đảo là không gian trọng yếu để phát triển văn hóa.", "Biển đảo là nguồn cung cấp lương thực chủ yếu cho cuộc sống của nhân dân Việt Nam."], ans: 1 },
  { q: "Đặc điểm chung về vị trí địa lý của quần đảo Hoàng Sa và Trường Sa là", opts: ["Gần với khu vực đất liền Việt Nam nhất.", "Nằm ở vị trí trung tâm của Biển Đông.", "Đều thuộc khu vực miền Bắc Việt Nam.", "Đều thuộc khu vực miền Nam Việt Nam."], ans: 1 },
  { q: "Cả hai quần đảo Hoàng Sa và Trường Sa đều tạo thuận lợi để Việt Nam phát triển ngành kinh tế nào sau đây?", opts: ["Nông nghiệp lúa nước.", "Lâm nghiệp.", "Công nghiệp chế tạo.", "Khai thác hải sản."], ans: 3 },
];

const TF_B12 = [
  { q: "Đọc đoạn tư liệu sau đây:\n\"Biển Đông là tên do người Việt Nam đặt từ xa xưa cho vùng biển nằm ở phía đông đất nước (Dư địa chí của Nguyễn Trãi năm 1435). Tên tiếng Anh của Biển Đông là South China Sea, do tổ chức Thủy đạc quốc tế đặt theo thông lệ quốc tế dựa vào tên địa danh của một quốc gia ven biển có diện tích lãnh thổ đất liền lớn nhất nhưng tên gọi này không hàm ý về chủ quyền. Người Trung Quốc gọi là Nam Hải, người Phi-lip-pin gọi là Biển Tây\".\n(Sách giáo khoa Lịch sử 11, Bộ chân trời sáng tạo, tr.77)", items: [
    { text: "Biển Đông có nhiều tên gọi khác nhau tùy theo cách gọi của từng quốc gia.", ans: true },
    { text: "Tổ chức Thủy đạc quốc tế đặt tên cho Biển Đông là South China Sea vì Trung Quốc là quốc gia ven Biển Đông có diện tích lớn nhất.", ans: true },
    { text: "Theo tổ chức Thủy đạc quốc tế, Biển Đông là vùng biển thuộc chủ quyền duy nhất của Trung Quốc.", ans: false },
    { text: "Biển Đông là tên do người Việt Nam đặt do vùng biển này nằm ở phía đông đất nước ta, nhưng người Phi-lip-pin lại gọi là Biển Tây vì vùng biển này nằm ở phía tây đất nước Phi-lip-pin.", ans: true }
  ]},
  { q: "Đọc đoạn tư liệu sau đây:\n\"Biển Đông là nơi cư trú của 12 nghìn loài sinh vật, trong đó có khoảng 2040 loài cá, 350 loài san hô, 662 loài rong biển, 12 loài có vú… Trong khu vực này, tập trung 221 loài cây nước mặn tạo nên diện tích rừng ngập mặn tương đối lớn. Khu vực thềm lục địa của biển Đông có tiềm năng dầu khí cao như bồn trũng Bru-nây, Nam Côn sơn, Hoàng Sa,…\"\n(Nguyễn Văn Âu, Địa lí tự nhiên Biển Đông, NXB Đại học Quốc gia Hà Nội, 2002, tr.33, 71–72)", items: [
    { text: "Đoạn trích cung cấp thông tin về nguồn tài nguyên thiên nhiên phong phú ở Biển Đông.", ans: true },
    { text: "Nguồn tài nguyên sinh vật ở Biển Đông rất phong phú đa dạng, nhưng chỉ có động vật mà không có thực vật.", ans: false },
    { text: "Dầu khí là một trong những nguồn tài nguyên khoáng sản đặc biệt quan trọng ở Biển Đông.", ans: true },
    { text: "Nguồn dầu khí ở Biển Đông chỉ có thể được khai thác ở 3 địa điểm: bồn trũng Bru-nây, Nam Côn sơn, Hoàng Sa.", ans: false }
  ]},
  { q: "Đọc đoạn tư liệu sau đây:\n\"Quần đảo Hoàng Sa (trực thuộc huyện đảo Hoàng Sa, thành phố Đà Nẵng) bao gồm hai nhóm đảo chính: nhóm phía tây (nhóm Lưỡi Liềm hay Trăng Khuyết) gồm một số đảo như Hoàng Sa, Tri Tôn, Hữu Nhật, Duy Mộng,…; nhóm phía đông (nhóm An Vĩnh) gồm các đảo tương đối lớn như Phú Lâm, Đa Cây, Linh Côn và các bãi ngầm, trong đó lớn nhất là đảo Phú Lâm. Quần đảo Trường Sa (trực thuộc huyện đảo Trường Sa, tỉnh Khánh Hòa) được chia thành 8 cụm là Song Tử, Loại Ta, Thị Tứ, Nam Yết, Sinh Tồn, Trường Sa, Thám Hiểm (An Bang) và Bình Nguyên\".\n(Sách giáo khoa Lịch sử 11, Bộ cánh diều, tr.81)", items: [
    { text: "Đoạn tư liệu cung cấp thông tin về tiềm năng phát triển du lịch của hai quần đảo Hoàng Sa và Trường Sa.", ans: false },
    { text: "Quần đảo Hoàng Sa và quần đảo Trường Sa lần lượt trực thuộc thành phố Đà Nẵng và tỉnh Khánh Hòa.", ans: true },
    { text: "Đảo Phú Lâm là một trong những đảo lớn nhất thuộc nhóm phía đông của quần đảo Hoàng Sa.", ans: true },
    { text: "Nhóm đảo Loại Ta là 1 trong 8 cụm thuộc quần đảo Trường Sa.", ans: true }
  ]},
  { q: "Đọc đoạn tư liệu sau đây:\nBiển Đông là mạch đường thiết yếu vận chuyển dầu và các nguồn tài nguyên thương mại từ Trung Cận Đông và Đông Nam Á tới Nhật Bản, Hàn Quốc và Trung Quốc. Hơn 90% lượng vận tải thương mại của thế giới thực hiện bằng đường biển và 45% trong số đó phải đi qua vùng biển Đông. Nhiều nước và vùng lãnh thổ ở khu vực Đông Á có nền kinh tế phụ thuộc sống còn vào con đường biển này như: Nhật Bản, Hàn Quốc, Đài Loan, Xingapo và Trung Quốc. Hàng năm, có khoảng 70% khối lượng dầu mỏ nhập khẩu được vận chuyển bằng đường biển qua biển Đông. Trung Quốc có 29/39 tuyến đường hàng hải và khoảng 60% lượng hàng hóa xuất nhập khẩu, 70% lượng dầu mỏ nhập khẩu được vận chuyển bằng đường biển qua biển Đông. Ven Biển Đông có hơn 500 cảng biển, trong đó có 2 cảng vào loại lớn và hiện đại nhất thế giới là cảng Xin-ga-po và Hồng Công.", items: [
    { text: "Những dẫn chứng được đưa ra trong đoạn tư liệu cho thấy Biển Đông là tuyến đường giao thông biển huyết mạch của khu vực châu Á – Thái Bình Dương.", ans: true },
    { text: "Nhiều quốc gia và vùng lãnh thổ thuộc khu vực Đông Bắc Á và Đông Nam Á có nền kinh tế phụ thuộc trực tiếp vào Biển Đông.", ans: true },
    { text: "Tất cả các tuyến đường hàng hải của Trung Quốc để xuất nhập khẩu hàng hóa, đặc biệt là dầu mỏ đều phải đi qua Biển Đông.", ans: false },
    { text: "Xin-ga-po và Hồng Công là hai cảng biển lớn và hiện đại nhất ở khu vực ven Biển Đông.", ans: true }
  ]},
  { q: "Đọc đoạn tư liệu sau đây:\nCác nước giáp Biển Đông có sản lượng đánh bắt và nuôi trồng hải sản đứng hàng đầu thế giới như: Trung Quốc, Thái Lan, Việt Nam, In-đô-nê-xi-a và Phi-lip-pin. Theo tổ chức Lương thực và Nông nghiệp Liên hợp quốc (FAO), Biển Đông là vùng biển có sản lượng đánh bắt hải sản hàng đầu thế giới với khoảng 6 triệu tấn, chiếm 10% tổng khối lượng toàn thế giới, riêng sản lượng cá xếp thứ 4/19 thế giới.\n(Sách giáo khoa Lịch sử 11, bộ Kết nối tri thức với cuộc sống, tr.76)", items: [
    { text: "Những dẫn chứng được đưa ra trong đoạn tư liệu cho thấy Biển Đông có tầm quan trọng chiến lược về kinh tế, chính trị - an ninh với nhiều quốc gia.", ans: true },
    { text: "Theo tổ chức UNESCO, Biển Đông là vùng biển có sản lượng đánh bắt hải sản hàng đầu thế giới.", ans: false },
    { text: "Việt Nam là một trong những quốc gia ven Biển Đông có sản lượng đánh bắt hải sản đứng hàng đầu thế giới.", ans: true },
    { text: "Biển Đông là vùng biển có sản lượng đánh bắt hải sản chiếm tỉ lệ gần như tuyệt đối trên toàn thế giới.", ans: false }
  ]}
];

const MC_B13 = [
  { q: "Khu vực nào của Việt Nam KHÔNG giáp với Biển Đông?", opts: ["Tây Bắc.", "Đông Bắc.", "Tây Nam.", "Đông Nam."], ans: 0 },
  { q: "Bờ biển nước ta dài khoảng 3260 km, kéo dài từ", opts: ["Tỉnh Quảng Ninh đến tỉnh Kiên Giang.", "Tỉnh Quảng Ninh đến tỉnh An Giang.", "Tỉnh Thái Bình đến tỉnh Cà Mau.", "Tỉnh Nam Định đến tỉnh Bình Thuận."], ans: 0 },
  { q: "Nội dung nào sau đây phản ánh đúng tầm quan trọng của Biển Đông về quốc phòng, an ninh đối với Việt Nam?", opts: ["Tạo điều kiện thuận lợi phát triển kinh tế biển đa dạng.", "Là cửa ngõ, tuyến phòng thủ bảo vệ đất liền từ xa.", "Là con đường giao thương giữa các vùng trong cả nước.", "Tạo thuận lợi cho Việt Nam phát triển thương mại hàng hải."], ans: 1 },
  { q: "Biển Đông nước ta góp phần quan trọng vào việc phát triển các ngành kinh tế trọng điểm, NGOẠI TRỪ", opts: ["Nông nghiệp trồng lúa nước.", "Thương mại hàng hải.", "Nuôi trồng thủy sản.", "Du lịch - dịch vụ."], ans: 0 },
  { q: "Về quốc phòng, an ninh, tầm quan trọng của Biển Đông đối với Việt Nam được thể hiện ở điểm nào sau đây?", opts: ["Là nơi có trữ lượng dầu khí lớn nhất thế giới.", "Là nơi có nguồn tài nguyên sinh vật đa dạng.", "Là khu vực tập trung các tuyến đường chiến lược.", "Là tuyến phòng thủ từ phía đông của đất nước."], ans: 3 },
  { q: "Hệ thống các cảng nước sâu và cảng trung bình được xây dựng dọc Biển Đông là điều kiện thuận lợi cho Việt Nam phát triển ngành kinh tế chủ yếu nào sau đây?", opts: ["Nông nghiệp lúa nước.", "Thương mại hàng hải.", "Nuôi trồng thủy sản.", "Khai thác tài nguyên biển."], ans: 1 },
  { q: "Với vị trí địa lý và tài nguyên phong phú của Biển Đông, Việt Nam có thể khai thác phát triển nhiều ngành mũi nhọn, NGOẠI TRỪ", opts: ["Giao thông hàng hải.", "Du lịch biển.", "Công nghiệp khai khoáng.", "Chăn nuôi gia cầm."], ans: 3 },
  { q: "Nội dung nào sau đây KHÔNG phản ánh đúng tầm quan trọng của Biển Đông về kinh tế đối với Việt Nam?", opts: ["Là con đường để Việt Nam giao lưu, hội nhập với các nền văn hóa khác.", "Là cửa ngõ để Việt Nam giao lưu kinh tế với các nước khác trên thế giới.", "Cung cấp tiềm năng bảo tồn đa dạng sinh học biển và nguồn giống hải sản.", "Tạo điều kiện thuận lợi để phát triển đa dạng nhiều loại hình du lịch biển."], ans: 0 },
  { q: "Một trong những bãi biển nổi tiếng của nước ta ở miền Trung, là địa điểm thu hút khách du lịch trong và ngoài nước là", opts: ["Hạ Long.", "Đà Nẵng.", "Phú Quốc.", "Cát Bà."], ans: 1 },
  { q: "Cảnh quan ở Biển Đông đa dạng với nhiều bãi cát, vịnh, hang động, tạo điều kiện cho Việt Nam phát triển ngành kinh tế mũi nhọn nào sau đây?", opts: ["Khai khoáng.", "Du lịch.", "Thương mại.", "Hàng hải."], ans: 1 },
  { q: "Một trong những nguồn tài nguyên quan trọng nhất ở thềm lục địa Việt Nam ở Biển Đông là", opts: ["Dầu khí.", "Gỗ lim.", "Cánh kiến.", "Đồi mồi."], ans: 0 },
  { q: "Nguồn tài nguyên phong phú của Biển Đông đã tạo điều kiện thuận lợi để Việt Nam phát triển ngành", opts: ["Dệt may.", "Khai khoáng.", "Hàng không.", "Da giầy."], ans: 1 },
  { q: "Quốc gia đầu tiên khai phá, xác lập chủ quyền và quản lý liên tục đối với quần đảo Trường Sa và Hoàng Sa là", opts: ["Việt Nam.", "Trung Quốc.", "Thái Lan.", "Campuchia."], ans: 0 },
  { q: "Một trong những công trình sử học và địa lí ghi chép về cương vực, lãnh thổ và hoạt động thực thi, bảo vệ chủ quyền của nhà nước phong kiến Việt Nam ở quần đảo Hoàng Sa, quần đảo Trường Sa là", opts: ["Đại Nam thực lục.", "Hịch tướng sĩ.", "Bình Ngô đại cáo.", "Ức Trai thi tập."], ans: 0 },
  { q: "Từ thế kỉ XVII đến thế kỉ XIX, tổ chức nào sau đây có nhiệm vụ đến khai thác sản vật, thực thi chủ quyền tại quần đảo Hoàng Sa và Trường Sa?", opts: ["Đội Hoàng Sa, Bắc Hải.", "Đội Trường Sa, Bắc Hải.", "Đội Hoàng Sa, Trường Sa.", "Đội Nam Hải, Đông Hải."], ans: 0 },
  { q: "Dưới thời vua Minh Mạng, hoạt động khẳng định chủ quyền đối với quần đảo Hoàng Sa và Trường Sa được thể hiện qua việc", opts: ["Thành lập các xã đảo, huyện đảo.", "Dựng miếu, trồng cây ở một số đảo.", "Xây dựng các trạm khí tượng lớn.", "Xây dựng các trạm vô tuyến điện."], ans: 1 },
  { q: "Dưới thời kì nhà Nguyễn, một trong những biện pháp của Nhà nước nhằm xác lập chủ quyền và quản lý đối với hai quần đảo Hoàng Sa và Trường Sa là", opts: ["Xây dựng trạm vô tuyến điện.", "Khảo sát đo vẽ bản đồ.", "Thành lập các huyện đảo.", "Xây dựng ngọn hải đăng."], ans: 1 },
  { q: "Nội dung nào sau đây KHÔNG phản ánh đúng nhiệm vụ của hải đội Hoàng Sa và Bắc Hải dưới triều Nguyễn?", opts: ["Dựng miếu thờ và trồng cây ở một số đảo.", "Đo đạc và cắm dấu mốc tại nơi khảo sát.", "Ngăn tàu thuyền nước ngoài đến buôn bán.", "Tiến hành thu gom, khai thác sản vật biển."], ans: 2 },
  { q: "Trong những năm 30 của thế kỉ XX, chính quyền Pháp đại diện cho Việt Nam trong quan hệ đối ngoại đã khẳng định chủ quyền của Việt Nam đối với quần đảo Hoàng Sa và Trường Sa thông qua việc", opts: ["Thành lập đội Hoàng Sa.", "Thành lập đội Bắc Hải.", "Xây dựng trạm khí tượng.", "Xây dựng sân bay lớn."], ans: 2 },
  { q: "Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam đã khẳng định chủ quyền của Việt Nam đối với quần đảo Hoàng Sa và Trường Sa thông qua việc", opts: ["Thành lập huyện đảo Hoàng Sa và Trường Sa.", "Thành lập đội Hoàng Sa, Bắc Hải và Trường Đà.", "Cho hoàn thiện tập Đại Nam nhất thống toàn đồ.", "Cử thủy quân ra tuần tra đảo định kì hàng năm."], ans: 0 },
  { q: "Từ cuối thế kỉ XIX đến năm 1945, quốc gia nào đại diện cho quyền lợi của Việt Nam tiếp tục khẳng định chủ quyền đối với quần đảo Hoàng Sa và Trường Sa?", opts: ["Trung Quốc.", "Anh.", "Mĩ.", "Pháp."], ans: 3 },
  { q: "Sau khi Pháp rút khỏi Việt Nam theo Hiệp định Giơnevơ (1954), lực lượng nào sau đây đã tiếp quản và khẳng định chủ quyền đối với quần đảo Hoàng Sa và Trường Sa?", opts: ["Chính quyền Sài Gòn.", "Chính quyền Bảo Đại.", "Chính quyền Pháp.", "Chính phủ Việt Nam dân chủ cộng hòa."], ans: 0 },
  { q: "Nhằm bảo vệ và thực thi chủ quyền, các quyền và lợi ích hợp pháp của Việt Nam ở Biển Đông, biện pháp nào sau đây KHÔNG được nhà nước Việt Nam áp dụng?", opts: ["Chủ động tấn công vũ trang.", "Tuyên truyền chủ quyền biển, đảo.", "Đàm phán ngoại giao.", "Xây dựng lực lượng quản lý biển."], ans: 0 },
  { q: "Nội dung nào sau đây KHÔNG phải là hoạt động của Việt Nam để bảo vệ chủ quyền biển đảo hiện nay?", opts: ["Kí kết với các nước láng giềng một số văn kiện ngoại giao quốc tế về biển.", "Tham gia Công ước Luật biển năm 1982 của tổ chức Liên hợp quốc.", "Chủ động tấn công ngăn chặn các nước có ý đồ xâm phạm biển.", "Thực hiện đầy đủ Tuyên bố về ứng xử của các bên ở Biển Đông."], ans: 2 },
  { q: "Chủ trương nhất quán của nước Cộng hòa xã hội chủ nghĩa Việt Nam trong việc giải quyết các tranh chấp ở Biển Đông hiện nay là", opts: ["Đấu tranh hòa bình.", "Bạo lực cách mạng.", "Chiến tranh cách mạng.", "Bãi công, bãi khóa."], ans: 0 },
  { q: "Văn kiện nào sau đây được kí kết giữa các nước ASEAN và Trung Quốc nhằm duy trì hòa bình và ổn định ở Biển Đông?", opts: ["Luật Biển Việt Nam.", "Tuyên bố về ứng xử của các bên ở Biển Đông.", "Luật Biên giới quốc gia.", "Tuyên bố về các vùng biển và thềm lục địa Việt Nam."], ans: 1 },
  { q: "Văn kiện nào sau đây do Nhà nước Việt Nam ban hành, khẳng định chủ quyền của nước ta đối với quần đảo Hoàng Sa và Trường Sa?", opts: ["Công ước Liên hợp quốc về Luật biển.", "Tuyên bố về ứng xử của các bên ở Biển Đông.", "Luật Cảnh sát biển Việt Nam.", "Hiến chương Liên hợp quốc."], ans: 2 },
  { q: "Tại hội nghị Hoà bình Xan Phran-xi-xcô (1951), khi chủ quyền của Việt Nam đối với quần đảo Hoàng Sa và quần đảo Trường Sa tiếp tục được tuyên bố mà không bị các quốc gia tham dự hội nghị phản đối. Điều đó cho thấy", opts: ["Tính pháp lý quốc tế và lịch sử về chủ quyền của Việt Nam.", "Đây là những quần đảo không có giá trị cao về kinh tế.", "Đây là những quần đảo không có giá trị cao về quốc phòng.", "Các quốc gia tham dự hội nghị đều tuyệt đối tôn trọng luật Biển."], ans: 0 },
  { q: "Nội dung nào sau đây là một trong những khó khăn của Việt Nam trong việc bảo vệ quyền, chủ quyền và các lợi ích hợp pháp trên Biển Đông hiện nay?", opts: ["Sự bất đồng về quan điểm giữa các bên liên quan đến Biển Đông.", "Lực lượng quân sự của ta quá yếu so với các nước Đông Nam Á.", "Các Ủy viên thường trực của Liên Hợp Quốc đều ủng hộ Trung Quốc.", "Thiếu các bằng chứng pháp lí để khẳng định chủ quyền ở Biển Đông."], ans: 0 },
  { q: "\"Xin hòa mình vào mênh mông biển cả / Hát ru Người yên giấc ngủ ngàn thu / 64 người nhắm mắt để triệu người choàng tỉnh / Trái tim đập dồn về phía Trường Sa\"\nNhững câu thơ trên nhắc đến sự kiện lịch sử nào sau đây trong quá trình đấu tranh bảo vệ chủ quyền biển đảo của Việt Nam ở Biển Đông?", opts: ["Pháp chuyển quyền kiểm soát Hoàng Sa và Trường Sa cho Bảo Đại.", "Cuộc chiến đấu của các chiến sĩ hải quân Việt Nam trên đảo Gạc Ma.", "Việt Nam đàm phán và kí kết Tuyên bố về ứng xử của các bên ở Biển Đông.", "Quân giải phóng miền Nam tiếp quản Trường Sa từ chính quyền Sài Gòn."], ans: 1 },
];

const TF_B13 = [
  { q: "Đọc đoạn tư liệu sau đây:\nBiển Đông có nguồn tài nguyên sinh vật phong phú và đa dạng, có đến hơn 160 000 loài, gần 10000 loài thực vật và 260 loài chim sống ở biển. Trong đó, trữ lượng cá ở vùng biển nước ta khoảng 5 triệu tấn/năm, trữ lượng cá có thể đánh bắt hàng năm khoảng 2,3 triệu tấn. Trữ lượng dầu mỏ và khí đốt ở thềm lục địa Việt Nam được xác minh là gần 550 triệu tấn dầu và trên 610 tỉ m3 khí…. Bờ biển Việt Nam dài và có nhiều bãi cát, vịnh, hang động tự nhiên đẹp như Hạ Long, Hải Phòng, Đà Nẵng, Quy Nhơn, Nha Trang, Vũng Tàu, Hà Tiên,… là tiềm năng cho phát triển kinh tế du lịch. Đặc biệt, hệ thống ven biển của Việt Nam có nhiều địa điểm thuận lợi cho việc xây dựng các cảng nước sâu và trung bình, phục vụ tốt cho sự phát triển kinh tế đất nước.\n(Sách giáo khoa Lịch sử 11, Bộ chân trời sáng tạo, tr.85)", items: [
    { text: "Toàn bộ đoạn tư liệu cung cấp thông tin về sự phát triển của ngành khai thác và nuôi trồng thủy, hải sản ở nước ta.", ans: false },
    { text: "Tài nguyên sinh vật ở Biển Đông bao gồm hai loại là thực vật và chim.", ans: false },
    { text: "Việt Nam có nhiều tiềm năng phát triển du lịch biển do có nhiều vịnh, hang động, bờ biển đẹp ven Biển Đông.", ans: true },
    { text: "Các cảng nước sâu và trung bình được xây dựng ven Biển Đông liên quan trực tiếp đến sự phát triển kinh tế của đất nước.", ans: true }
  ]},
  { q: "Đọc đoạn tư liệu sau đây:\n\"Họ Nguyễn đặt đội Hoàng Sa 70 suất, lấy người xã An Vĩnh sung vào, cắt phiên mỗi năm cứ tháng 2 nhận giấy sai đi, mang lương đủ ăn sáu tháng, đi bằng năm chiếc thuyền nhỏ, ra biển ba ngày ba đêm thì đến đảo ấy. Lấy được hoá vật của tàu như là gươm ngựa, hoa bạc, hòn bạc, đổ đổng, khối chì, súng, ngà voi, đổ sứ, đổ chiêm, cùng là vỏ đồi mồi, hải sâm, hạt ốc vân rất nhiều... Đến kì tháng 8 thì về. Họ Nguyễn lại đặt đội Bắc Hải. Lệnh cho đi chiếc thuyền câu nhỏ ra các xứ Bắc Hải, cù lao Côn Lôn và các đảo ở Hà Tiên\".\n(Theo Lê Quý Đôn, Phủ biên tạp lục, NXB Văn hoá - Thông tin, 2007, tr. 155)", items: [
    { text: "Đoạn trích trong cuốn Phủ biên tạp lục của Lê Quý Đôn trình bày quá trình hình thành và phát triển của quần đảo Hoàng Sa.", ans: false },
    { text: "Nhà Nguyễn đặt đội Hoàng Sa và đội Bắc Hải nhằm thực hiện quyền quản lý của mình đối với quần đảo Hoàng Sa và Trường Sa.", ans: true },
    { text: "Đội Hoàng Sa do nhà Nguyễn thành lập gồm 70 người, thực hiện nhiệm vụ của mình tại quần đảo Hoàng Sa định kì hàng năm từ tháng 2 đến tháng 10.", ans: false },
    { text: "Một trong những nhiệm vụ của đội Hoàng Sa và đội Bắc Hải là khai thác sản vật, thu lượm hàng hóa của những con tàu gặp nạn ở quần đảo Hoàng Sa và Trường Sa.", ans: true }
  ]},
  { q: "Đọc đoạn tư liệu sau đây:\n\"Tháng 7 - 1803, vua Gia Long cho lập lại đội Hoàng Sa, lấy Cai cơ Võ văn Phú làm Thủ ngự cửa biển Sa Kỳ, sai mộ dân ngoại tịch lập làm đội Hoàng Sa. Đầu năm 1815, vua Gia Long tiếp tục 'sai bọn Phạm Quang Ảnh thuộc đội Hoàng Sa ra Hoàng Sa xem xét đo đạc thủy trình…'. Năm 1816, vua Gia Long cho lực lượng ra quần đảo Hoàng Sa cắm cờ để xác định chủ quyền. Sang đời Minh Mạng, việc đo đạc thủy trình chủ yếu giao cho thủy quân thực hiện. Trong các năm 1833, 1834, 1836, vua Minh Mạng đã chỉ thị cho Bộ Công phái người ra Hoàng Sa để dựng bia chủ quyền, đo đạc thủy trình, vẽ bản đồ… Mỗi thuyền vãng thám Hoàng Sa phải đem theo 10 tấm bài gỗ dài 4,5 thước, rộng 5 tấc để dựng làm dấu mốc\".\n(Sách giáo khoa Lịch sử 11, Bộ chân trời sáng tạo, tr.86)", items: [
    { text: "Đoạn tư liệu cung cấp thông tin về hoạt động xác lập chủ quyền và quản lý đối với quần đảo Hoàng Sa của một số vị vua nhà Nguyễn thế kỉ XVIII.", ans: false },
    { text: "Đội Hoàng Sa đã được thành lập từ thời kì trước, sau đó vua Gia Long đã cho tái lập.", ans: true },
    { text: "Một trong những hoạt động của vua Minh Mạng nhằm xác lập chủ quyền và quản lý đối với quần đảo Hoàng Sa là cho thủy quân dựng bia chủ quyền và vẽ bản đồ.", ans: true },
    { text: "Đoạn tư liệu cho thấy ý thức về việc xác lập chủ quyền và quản lý đối với quần đảo Hoàng Sa của vua Gia Long và Minh Mạng chưa cao.", ans: false }
  ]},
  { q: "Đọc đoạn tư liệu sau đây:\nĐại Nam nhất thống toàn đồ là bản đồ Việt Nam dưới thời Nguyễn, được vẽ vào khoảng năm 1838, ghi rõ \"Hoàng Sa\", \"Vạn Lý Trường Sa\" thuộc lãnh thổ Việt Nam, phía ngoài các đảo ven bờ miền Trung Việt Nam thuộc lãnh thổ Việt Nam. Trong bài \"Địa lý Vương quốc Cô-chin-chi-na\" (Tạp chí Hội Địa lí Hoàng gia Luân Đôn, Tập 19, 1849, tr.93) của Gút-láp, có đoạn ghi rõ Pa-ra-xeo (tức Hoàng Sa) thuộc lãnh thổ Việt Nam và chú thích cả tên Việt Nam là \"Cát Vàng\".\n(Sách giáo khoa Lịch sử 11, Bộ Cánh diều, tr.86)", items: [
    { text: "Đại Nam nhất thống toàn đồ là bản đồ Việt Nam dưới thời Nguyễn, được vẽ vào thế kỉ XVIII.", ans: false },
    { text: "Đại Nam nhất thống toàn đồ là một tài liệu, căn cứ để khẳng định Hoàng Sa và Trường Sa trong lịch sử thuộc chủ quyền của Việt Nam.", ans: true },
    { text: "Chủ quyền của Việt Nam đối với quần đảo Hoàng Sa còn được ghi chép trong các tài liệu của người nước ngoài.", ans: true },
    { text: "Đại Nam nhất thống toàn đồ là tấm bản đồ duy nhất của Việt Nam hiện nay thể hiện Hoàng Sa và Trường Sa thuộc lãnh thổ Việt Nam.", ans: false }
  ]},
  { q: "Đọc đoạn tư liệu sau đây:\nVới chủ trương nhất quán giải quyết các tranh chấp, bất đồng trên biển bằng biện pháp hòa bình, Việt Nam đã có nhiều nỗ lực trong việc áp dụng có hiệu quả Công ước Liên hợp quốc về Luật Biển năm 1982 để giải quyết các tranh chấp về phân định biển với các nước láng giềng. Việt Nam đã chủ động cùng các quốc gia có liên quan đàm phán, phân định các vùng biển chồng lấn theo quy định của Công ước, góp phần tạo môi trường ổn định, hòa bình, hợp tác và phát triển, như kí thỏa thuận hợp tác cùng phát triển dầu khí với Ma-lai-xi-a (1992), phân định biển với Thái Lan (1997), phân định Vịnh Bắc Bộ với Trung Quốc (2000), phân định thềm lục địa với In-đô-nê-xi-a (2003).\n(Sách giáo khoa Lịch sử 11, Bộ Cánh diều, tr.89)", items: [
    { text: "Việt Nam chủ trương nhất quán giải quyết các tranh chấp trên Biển Đông thông qua biện pháp hòa bình, thương lượng.", ans: true },
    { text: "Công ước Liên hợp quốc về Luật Biển là một văn bản pháp lý quan trọng giúp Việt Nam có thể giải quyết các tranh chấp trên biển thông qua luật pháp quốc tế.", ans: true },
    { text: "Việt Nam đã chủ động đàm phán và kí kết thỏa thuận với nhiều quốc gia có chung Biển Đông nhằm đảm bảo hòa bình, an ninh trên biển.", ans: true },
    { text: "In-đô-nê-xi-a và Việt Nam đã đàm phán và cùng đi đến thỏa thuận hợp tác phát triển dầu khí trên biển năm 2003.", ans: false }
  ]}
];
